/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppHeader: typeof import('./src/components/AppHeader.vue')['default']
    Button: typeof import('primevue/button')['default']
    Card: typeof import('primevue/card')['default']
    OrdenCard: typeof import('./src/components/OrdenCard.vue')['default']
    OrderSummary: typeof import('./src/components/OrderSummary.vue')['default']
    ProductCard: typeof import('./src/components/ProductCard.vue')['default']
    ProductFilters: typeof import('./src/components/ProductFilters.vue')['default']
    ProductListing: typeof import('./src/components/ProductListing.vue')['default']
    RadioButton: typeof import('primevue/radiobutton')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
